services:
  app1:
    build: ./app1
    container_name: app1
    command: uvicorn server:app --reload --host=0.0.0.0 --port=8001
    ports:
      - 8001:8001
    volumes:
      - ./app1:/app
    networks:
      my_shared_network:
        aliases:
          - app1

  app2:
    build: ./app2
    container_name: app2
    command: uvicorn server:app --reload --host=0.0.0.0 --port=8002
    ports:
      - 8002:8002
    volumes:
      - ./app2:/app
    networks:
      my_shared_network:
        aliases:
          - app2

networks:
    my_shared_network:
      driver: bridge